9fans/go

acme/acme.go
When the call to fid generates an error,
Write returns a nil error.
This makes it look like Write succeeded
even though it was called with an unknown file, say.
=> Win.Write: Return errors from fid

draw/getsubfont.go, draw/openfont.go
go test 1.10 runs go vet prior to running the tests and so fails when
formatting directives are used as arguments to log.Fatal in draw
test code. Change these calls to log.Fatalf
=> draw: update test code for go test 1.10

draw/getsubfont.go, draw/unloadimage.go
In draw, scalesubfont is executed within the context of an existing
lock and attempts to reacquire the lock when creating synthetic
high-dpi versions of fonts. Change scalesubfont to use draw's private
unlocked methods.
=> draw: fix reentrant lock in scalesubfont

plumb/plumb.go
plumb.Recv reads plumber messages from an underlying io.Reader.
io.Reader implementations may choose to return less than the requested
number of bytes particularly when a plumber message is large (e.g.
plumb 'frame(3)') so use io.ReadFull to read the entire message.
=> plumb: Always read entire message in plumb.Recv

acme/acme.go
Useful to identify events in the log for a window created with New().
=> acme: allow get the ID for a Win

draw/poly.go
This patch fixes an error in the dopoly function, where the buffer size o
is mistakenly set rather than added to. This causes the message buffer to
be truncated and the appearance of the error 'flush: short draw message
errors.'
=> draw: fix buffer size calculation in dopoly function

acme/acme.go, plan9/client/fid.go
Satisfy this requirement of io.ReaderAt:
When ReadAt returns n < len(p), it returns a non-nil error
explaining why more bytes were not returned.
In other words, when EOF is reached and 0 < n < len(p), io.EOF error
must be returned. ReadAt was delaying sending io.EOF until n == 0.
Satisfying io.ReaderAt makes it possible to substitute Fid with os.File
in Plan 9.
=> plan9/client: make ReadAt compatible with io.ReaderAt interface

acme/acme.go
This allows custom plumbing rules to take effect when the window is controlled by an external program.
i.e. right-clicking acme(1) in an external program's window doesn't work the same as right-clicking it in an acme-controlled window.
=> acme.WriteEvent should write back original empty selections

draw/buildfont.go, draw/init.go
Fix a possible scenario when`d == nil`, dereferencing would cause `panic`.
=> draw: fix nil pointer dereference for (*Display).Close method

acme/Watch/main.go
Using kill() avoids child processes to stay running in the background.
This is specially relevant when running programs like servers, which
have to be terminated explicitly. If they are not killed, processes
would be leaked or successive runs could fail due to unreleased
resources (e.g. network ports).
For instance, when developing simple servers, I commonly run Watch
this way:
```
Watch -r 'go build && ./server -addr=:6060' 
```
If child processes are not killed, next runs would fail because the
listen address is still in use. The changes introduced in this pull
request allow to restart the server when changing files or executing
Get.
=> acme/Watch: use kill() to terminate the last running command

acme/acmego/main.go
Currently when a file doesn't have a final newline, acmego will always
say there's a difference because goimports always adds a newline
and `9 diff` doesn't report the difference. This change fixes that.
=> go/acme/acmego: cope with missing final newline

cmd/acme/internal/exec/exec.go
The previous logic had a bug where the command `foo bar baz arble` would
parse as`["foo" "foo bar" "foo bar baz" "arble"]` (the `ai` variable was never being updated).
Use `strings.Fields` instead.
=> cmd/acme/internal/exec: fix command parsing

cmd/acme/internal/dump/rows1.go
All files were being marked as dirty in the dump file.
The original C logic was:
```
}else if((w->dirty==FALSE && access(a, 0)==0) || w->isdir){
```
That is, the condition applies if it's not dirty and the file exists.
That logic wasn't kept in translation, so fix that.
=> cmd/acme/internal/dump: don't mark existing files as dirty

cmd/samterm/flayer.go
Fix loop range in `flresize()` and remove unused `nllist` so the layers are redrawn after a window resize
=> cmd/samterm: fix resize

cmd/sam/io.go
remoteFD should be created as IOFiles and not closed after execing
samterm.
Fixes #55
=> sam: Fix remote sam

acme/acme.go
This fixes an occasional panic I was seeing when using `acmego`. @rsc
=> acme: avoid crash when w.fid fails

cmd/acme/internal/edit/ecmd.go
I copied the logic from the C version:
```
while(p < f->b.nc && textreadc(f->curtext, p++)!='\n')
;
```
=> cmd/acme/internal/edit: fix infinite loop

draw/frame/frinsert.go, draw/frame/frutil.go
This fixes the issue where inserting some text on a wrapped line would cause the text to wrap at an inappropriate place.
Also add some comments to the frame code to try to make things easier for future maintainers. The comments may well be misguided though!
=> draw/frame: fix insertion

cmd/acme/internal/fileload/text1.go
The string wasn't being appropriately truncated so we were seeing
error messages like:
```
error attempting completion: open /home/rogpeppe/src/influx/openapi/contracts/\x00\x00....: invalid argument
```
Fix by using more natural Go idioms.
Closes #74.
=> cmd/acme/internal/fileload: fix completion logic

plan9/client/conn.go, plan9/client/fid.go, plan9/client/fsys.go
Implement `Fsys.Close` by closing its root `Fid`.
This needed a bunch of reworking to make refcounting of connections
work. We add a new method, `Conn.Release` which allows the
connection to be released when the last `Fid` derived from it
has been closed. The existing `Conn.Close` method retains its
old semantics for backward compatibility (arguably it might be better to change its semantics
and just let callers close the underlying connection directly themselves if they wish).
The closing logic was made more complex by the fact that a `Fid` could
represent both a fid that's been allocated on the server and a
fid that is about to be sent to the server for allocation.
Simplify the invariants by only creating a `Fid` object when we know
that the fid has actually been allocated on the …
=> plan9/client: refcounted Fsys

cmd/acme/internal/dump/rows1.go
See https://github.com/9fans/go/issues/68.
=> cmd/acme: make Load more resilient in the face of a bad tag

acme/acmego/main.go
When a line is being added to the start of a document
(a classic example being when `gofmt` adds a `//go:build` line),
the diff logic was ignoring it and thus always thinking that
the file needed changes without ever actually applying the
changes.
=> acme/acmego: allow append at 0

acme/acmego/main.go
Enable formatting of Python code with `acmego -f`.
=> acmego: Add Python formatter

cmd/sam/sam.go
I was getting this after a r command:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
```
=> sam: fix crash after r command

cmd/samterm/unix.go
I'm not well-versed on the subtleties around fd ints and the syscall package in go, but I was getting this error while trying to install the utils via `go install ./...`:
```
% go install ./...
cmd/samterm/unix.go:62:21: cannot use fd (variable of type int) as *os.File value in argument to extproc
```
=> fix compilation error on samterm

acme/Watch/main.go
I've found that it's not uncommon to be running Watch in a VCS directory, and in the course of rebasing, that directory is removed and created again. Because the Watch command is just run in the current directory, that causes it to fail.
This change uses an explicit directory for the command, which fixes that failure. A more complete solution would probably take the directory from the window's tag, but that would be more involved, because we'd also want to change the watched directory when that changes, so leave it for later.
=> acme/Watch: use explicit directory for running command
